trigger:
  branches:
    include:
      - main

# pr:
#   branches:
#     include:
#       - main

pool: selfhost-aks

variables:

  acrName: 'acrashudevka'
  acrLoginServer: 'acrashudevka.azurecr.io'

  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  buildContext: '$(Build.SourcesDirectory)'

  imageRepository: 'axion-ingestion-service'
  imageTag: '$(Build.BuildId)'

stages:

- stage: BuildAndPush
  displayName: 'Build and Push Ingestion Service'

  jobs:

  - job: BuildAndPush
    displayName: 'Build Docker Image and Push to ACR'

    steps:

    - checkout: self
      displayName: 'Checkout Source Code'

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(buildContext)'
        tags: |
          $(imageTag)

    - task: Docker@2
      inputs:
        containerRegistry: 'acr-svc-msi-1'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(buildContext)'
        tags: '$(imageTag)'

    - task: AzureCLI@3
      inputs:
        connectionType: 'azureRM'
        azureSubscription: 'SVC-AZ-ARM-250926'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name $(acrName)
          
          docker tag $(imageRepository):$(imageTag) $(acrLoginServer)/$(imageRepository):$(imageTag)
          
          docker push $(acrLoginServer)/$(imageRepository):$(imageTag)